# Generated by Django 2.2.2 on 2019-06-05 21:09

import core.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, default=' ', verbose_name='Number')),
                ('created_date', models.DateTimeField(blank=True, default=core.common.utils.random_date, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
