# Generated by Django 2.2.2 on 2019-06-06 09:35

import core.common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, default='', verbose_name='Number')),
                ('created_date', models.DateTimeField(blank=True, default=core.common.utils.random_date, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=55, verbose_name='Product')),
                ('product_price', models.PositiveIntegerField(blank=True, verbose_name='Price')),
                ('amount', models.PositiveIntegerField(blank=True, verbose_name='Amount')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.Order')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
