# Generated by Django 2.2.2 on 2019-06-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(blank=True, default='', verbose_name='Number'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=55, verbose_name='Product')),
                ('product_price', models.PositiveIntegerField(blank=True, verbose_name='Price')),
                ('amount', models.PositiveIntegerField(blank=True, verbose_name='Amount')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.Order')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
