# Generated by Django 2.2.2 on 2019-06-06 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 1, 10, 0), verbose_name='Created Date'),
        ),
    ]
