# Generated by Django 2.2.2 on 2019-06-08 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190606_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 1, 10, 0, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
