# Generated by Django 2.2.2 on 2019-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_queuetodbmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetodbmodel',
            name='product_by_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuetodbmodel',
            name='top_hundred',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
